### ISSUE TITLE
[Feedback] avoid generating `unknown.provider.json`

### ISSUE THREAD

**Issue by julpat** [superfaceai/cli#354]
### Feedback
After `superface prepare` users can get into a situation when `unknown.provider.json` is created. The next steps are confusing for the user (should I continue with "unknown" and get lost or do I must spend some time on it to find out why it is "unknown").
![image](https://github.com/superfaceai/cli/assets/6079287/1f55d7a8-60b8-4929-a38b-be88958118c2)

#### Possible solutions:
a) Find a different way how to get at least the provider name if generating the whole provider.json is not possible.
b) Ask for the provider's name before finishing the `prepare` command (if the name can not be created automatically).
c) Consider command execution as failed; Guide to run it again with the provider name argument.

cc @rak-superface

**Comment by Jakub-Vacek** [comment]
This was partially addressed in https://github.com/superfaceai/cli/pull/352 (for provider name inferred form filename).
b) - won't be possible because we would need to change our worker implementation.

Personally, I would go with C and we should also go through the cases when `unknown` happens and try to mitigate them.

**Comment by Jakub-Vacek** [comment]
PR mitigating this issue were merged and deployed
